  name: code-coverage-summary-action
  on:
    pull_request:
      branches: [ main ]
    workflow_dispatch:
  jobs:
    # Build job
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Code Coverage Summary
          # You may pin to the exact commit or the version.
          # uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95
          uses: irongut/CodeCoverageSummary@v1.3.0
          with:
            # A comma separated list of code coverage files to analyse. Also supports using glob patterns to match multiple files.
            filename: reports/cobertura.xml
            # Include a Line Rate coverage badge in the output using shields.io - true / false (default).
            # badge: # optional, default is false
            # Fail if overall Line Rate below lower threshold - true / false (default).
            # fail_below_min: # optional, default is false
            # Output Format - markdown or text (default).
            format: markdown # optional, default is text
            # Hide Branch Rate values in the output - true / false (default).
            # hide_branch_rate: # optional, default is false
            # Hide Complexity values in the output - true / false (default).
            # hide_complexity: # optional, default is false
            # Include health indicators in the output - true (default) / false.
            # indicators: # optional, default is true
            # Output Type - console (default), file or both.
            output: file # optional, default is console
            # Threshold percentages for badge and health indicators, lower threshold can also be used to fail the action.
            # thresholds: # optional, default is 50 75
        - name: Add Coverage PR Comment
          uses: marocchino/sticky-pull-request-comment@v2
          if: github.event_name == 'pull_request'
          with:
            recreate: true
            path: code-coverage-results.md
